<?php

use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $sql_query = "INSERT INTO `languages` (`name`,`iso_639_1`,`country_code`) VALUES('English', 'en','gb'),
                    ('Afar', 'aa','et'),
                    ('Abkhazian', 'ab','tr'),
                    ('Afrikaans', 'af','za'),
                    ('Amharic', 'am','et'),
                    ('Arabic', 'ar','iq'),
                    ('Assamese', 'as','in'),
                    ('Aymara', 'ay','pe'),
                    ('Azerbaijani', 'az','az'),
                    ('Bashkir', 'ba','ru'),
                    ('Belarusian', 'be','by'),
                    ('Bulgarian', 'bg','bg'),
                    ('ari', 'bh','et'),
                    ('lama', 'bi','mm'),
                    ('Bengali/Bangla', 'bn','bd'),
                    ('Tibetan', 'bo','cn'),
                    ('Breton', 'br','fr'),
                    ('Catalan', 'ca','es'),
                    ('Corsican', 'co','fr'),
                    ('Czech', 'cs','cz'),
                    ('Welsh', 'cy','gb'),
                    ('Danish', 'da','dk'),
                    ('German', 'de','de'),
                    ('Bhutani', 'dz','bt'),
                    ('Greek', 'el','gr'),
                    ('Esperanto', 'eo','bw'),
                    ('Spanish', 'es','es'),
                    ('Estonian', 'et','ee'),
                    ('Basque', 'eu','es'),
                    ('Persian', 'fa','ir'),
                    ('Finnish', 'fi','fi'),
                    ('Fiji', 'fj','fj'),
                    ('Faeroese', 'fo','dk'),
                    ('French', 'fr','fr'),
                    ('Frisian', 'fy','nl'),
                    ('Irish', 'ga','ie'),
                    ('Scots/Gaelic', 'gd','gb'),
                    ('Galician', 'gl','es'),
                    ('Guarani', 'gn','us'),
                    ('Gujarati', 'gu','in'),
                    ('Hausa', 'ha','ng'),
                    ('Hindi', 'hi','in'),
                    ('Croatian', 'hr','hr'),
                    ('Hungarian', 'hu','hu'),
                    ('Armenian', 'hy','am'),
                    ('Interlingua', 'ia','fr'),
                    ('Interlingue', 'ie','fr'),
                    ('Inupiak', 'ik','us'),
                    ('Indonesian', 'in','id'),
                    ('Icelandic', 'is','is'),
                    ('Italian', 'it','it'),
                    ('Hebrew', 'iw','il'),
                    ('Japanese', 'ja','jp'),
                    ('Yiddish', 'ji','eu'),
                    ('Javanese', 'jw','id'),
                    ('Georgian', 'ka','ge'),
                    ('Kazakh', 'kk','kz'),
                    ('Greenlandic', 'kl','gl'),
                    ('Cambodian', 'km','kh'),
                    ('Kannada', 'kn','in'),
                    ('Korean', 'ko','kr'),
                    ('Kashmiri', 'ks','in'),
                    ('Kurdish', 'ku','iq'),
                    ('Kirghiz', 'ky','kg'),
                    ('Latin', 'la','ba'),
                    ('Lingala', 'ln','cd'),
                    ('Laothian', 'lo','la'),
                    ('Lithuanian', 'lt','lt'),
                    ('Latvian/Lettish', 'lv','lv'),
                    ('Malagasy', 'mg','mg'),
                    ('Maori', 'mi','nz'),
                    ('Macedonian', 'mk','mk'),
                    ('Malayalam', 'ml','in'),
                    ('Mongolian', 'mn','mn'),
                    ('Moldavian', 'mo','md'),
                    ('Marathi', 'mr','in'),
                    ('Malay', 'ms','my'),
                    ('Maltese', 'mt','mt'),
                    ('Burmese', 'my','mm'),
                    ('Nauru', 'na','nr'),
                    ('Nepali', 'ne','np'),
                    ('Dutch', 'nl','nl'),
                    ('Norwegian', 'no','no'),
                    ('Occitan', 'oc','fr'),
                    ('(Afan)/Oromoor/Oriya', 'om','in'),
                    ('Punjabi', 'pa','in'),
                    ('Polish', 'pl','pl'),
                    ('Pashto/Pushto', 'ps','af'),
                    ('Portuguese', 'pt','pt'),
                    ('Quechua', 'qu','bo'),
                    ('Rhaeto-Romance', 'rm','ch'),
                    ('Kirundi', 'rn','bi'),
                    ('Romanian', 'ro','ro'),
                    ('Russian', 'ru','ru'),
                    ('Kinyarwanda', 'rw','rw'),
                    ('Sanskrit', 'sa','in'),
                    ('Sindhi', 'sd','in'),
                    ('Sangro', 'sg','cf'),
                    ('Serbo-Croatian', 'sh','rs'),
                    ('Singhalese', 'si','lk'),
                    ('Slovak', 'sk','sk'),
                    ('Slovenian', 'sl','si'),
                    ('Samoan', 'sm','as'),
                    ('Shona', 'sn','zw'),
                    ('Somali', 'so','so'),
                    ('Albanian', 'sq','al'),
                    ('Serbian', 'sr','cs'),
                    ('Siswati', 'ss','sz'),
                    ('Sesotho', 'st','za'),
                    ('Sundanese', 'su','id'),
                    ('Swedish', 'sv','se'),
                    ('Swahili', 'sw','ke'),
                    ('Tamil', 'ta','in'),
                    ('Telugu', 'te','in'),
                    ('Tajik', 'tg','tj'),
                    ('Thai', 'th','th'),
                    ('Tigrinya', 'ti','et'),
                    ('Turkmen', 'tk','tm'),
                    ('Tagalog', 'tl','ph'),
                    ('Setswana', 'tn','za'),
                    ('Tonga', 'to','to'),
                    ('Turkish', 'tr','tr'),
                    ('Tsonga', 'ts','za'),
                    ('Tatar', 'tt','ru'),
                    ('Twi', 'tw','gh'),
                    ('Ukrainian', 'uk','ua'),
                    ('Urdu', 'ur','pk'),
                    ('Uzbek', 'uz','uz'),
                    ('Vietnamese', 'vi','vn'),
                    ('Volapuk', 'vo','de'),
                    ('Wolof', 'wo','sn'),
                    ('Xhosa', 'xh','za'),
                    ('Yoruba', 'yo','ng'),
                    ('Chinese', 'zh','cn'),
                    ('Zulu', 'zu','za');";

        $count  =   DB::table('languages')->count();

        if(!$count){
            DB::statement($sql_query);
        }
    }
}
