<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MerchantMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $count  =   DB::table('merchant_menus')->count();

        if(!$count){

            DB::table('merchant_menus')->insert([
                [
                    'title'             =>      'Bookings',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      0,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],

                [
                    'title'             =>      'Reports',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      0,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Invoices',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      0,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Hotel',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      0,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Shop',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      0,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Dive Center',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      0,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Settings',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      0,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'All Bookings',
                    'as'                =>      'bookings::all_bookings',
                    'slug'              =>      null,
                    'parent_id'         =>      1,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'New Booking',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      1,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Icall Feed',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      1,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Icall Import',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      1,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Booking Settings',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      1,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],

                [
                    'title'             =>      'Charts',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      2,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Arriving Today',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      2,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Departure Today',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      2,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Cleaning Schedule',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      2,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Percentage Booked',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      2,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Report Settings',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      2,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],

                [
                    'title'             =>      'All Invoices',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      3,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'SCBY Invoices',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      3,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Guest Invoices',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      3,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Open Invoices',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      3,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Invoices Settings',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      3,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Room Features',
                    'as'                =>      'room_features',
                    'slug'              =>      'features',
                    'parent_id'         =>      4,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Room Types',
                    'as'                =>      'room_types',
                    'slug'              =>      'types',
                    'parent_id'         =>      4,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Manage Hotel',
                    'as'                =>      'hotels',
                    'slug'              =>      'hotels',
                    'parent_id'         =>      4,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Guests',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      4,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'All Guests',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      27,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'New Guests',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      27,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Guests Types',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      27,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Guests Settings',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      27,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Manage Shop',
                    'as'                =>      'shop::shops',
                    'slug'              =>      null,
                    'parent_id'         =>      5,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'All Shop Items',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      5,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Product Features',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      5,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Product Settings',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      5,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Product Categories',
                    'as'                =>      'shop::product_categories',
                    'slug'              =>      null,
                    'parent_id'         =>      5,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Manage Dive Centers',
                    'as'                =>      'dive_center::dive_centers',
                    'slug'              =>      null,
                    'parent_id'         =>      6,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Add Location',
                    'as'                =>      'dive_center::locations',
                    'slug'              =>      null,
                    'parent_id'         =>      6,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],

                [
                    'title'             =>      'Account Details',
                    'as'                =>      'settings::account_details',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Account Configuration',
                    'as'                =>      'settings::account_configuration',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Account Verification',
                    'as'                =>      'settings::account_verification',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Websites',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Users',
                    'as'                =>      'settings::users',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Contact Information',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Payment Gateways',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Pricing',
                    'as'                =>      'pricing_settings',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Tax Rates',
                    'as'                =>      'settings::tax_rates',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'API Keys',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Email Templates',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
                [
                    'title'             =>      'Media Center',
                    'as'                =>      '#',
                    'slug'              =>      null,
                    'parent_id'         =>      7,
                    'created_at'        =>      \Carbon\Carbon::now(),
                    'updated_at'        =>      \Carbon\Carbon::now(),
                ],
            ]);
        }
    }
}
